@Library('eleksCamp') _

pipeline{
    agent any 
    stages {
        stage('Build and archive'){
            steps{
                script{
                    buildAndArchive()
                    }
                }
            }
            stage ('Publish'){
                steps {
                    script{
                    publishToAzureArtifacts('another.great.mvc')
                    }
                }
            }
        
    }
    post{
        always {
            cleanWs()
        }
        
    }
}
